# Student Exam Score Analysis Using Python and NumPy

This notebook analyses student exam scores using Python and the NumPy library.



## Objectives

The objectives of this project are to:
- Understand overall student performance
- Identify top and bottom performing students
- Compare average scores across subjects
- Practise core NumPy operations



In [15]:
import numpy as np

## Student Exam Score Data

The data consists of student names and their exam scores in three subjects:
Math, Science, and English. NumPy arrays are used to efficiently perform
numerical operations on the data.


In [16]:
students = ["Sunny", "Peter", "Tilly", "Safiyyah", "Tara"]

math = [78, 88, 67, 90, 56]
science = [85, 79, 70, 95, 60]
english = [90, 92, 75, 93, 58]

## Converting Lists to NumPy Arrays

NumPy arrays allow numerical operations to be performed more efficiently than
standard Python lists. By converting the subject score lists into NumPy arrays,
we can easily calculate averages using built-in NumPy functions.


## NumPy Operations that will be utilized

The following core NumPy operations will be used in this project:
- 01. `np.array()` to store numerical data
- 02. `np.sum()` to calculate total scores
- 03. `np.mean()` to calculate average scores
- 04. `Array indexing` for data access
- 05. `np.argmax()` to identify the highest value
- 06. `np.argmin()` to identify the lowest value



In [17]:
#--- 01. Demonstrating np.array() by storing relevant data of student names and score for subjects such as Math, Science and English. ---

students_np = np.array(students)

math_np = np.array(math)
science_np = np.array(science)
english_np = np.array(english)


print(students_np)
print(math_np)
print(science_np)
print(english_np)

['Sunny' 'Peter' 'Tilly' 'Safiyyah' 'Tara']
[78 88 67 90 56]
[85 79 70 95 60]
[90 92 75 93 58]


In [19]:
# --- 02. The np.sum() function is used below to calculate each student’s total score across all three subjects. ---
# ---Loop through all students by their index ---
# ---len(students) gives the number of students, and range(...) generates indices 0 to n-1 ---

# Combine into a 2D array: rows = subjects, columns = students
scores_np = np.array([math_np, science_np, english_np])


total_scores = np.sum(scores_np, axis=0)

for i in range(len(students)):
    print(students[i], "total score:", total_scores[i])


Sunny total score: 253
Peter total score: 259
Tilly total score: 212
Safiyyah total score: 278
Tara total score: 174


## Overall Student Performance

Overall performance is analysed by calculating the total and average score for
each student across all subjects.



In [ ]:
# --- 03. The np.mean() function is used below to calculate each student’s average score across all subjects. ---

average_scores = np.mean(scores_np, axis=0)

# --- Loop through all students by index ---
# --- len(students) gives the total number of students ---
# --- range(len(students)) generates indices from 0 to n-1 ---
# --- Prints the student's name and their average score ---
# --- round(..., 2) rounds the score to 2 decimal places for readability ---


for i in range(len(students)):
    print(students[i], "average score", round(average_scores[i], 2))


In [ ]:
# --- 04. Array indexing is demonstrated by the below code to fetch the 4th student's average score across all subjects. --- 
# --- The array count begins from `0` ---

average_scores_per_student = np.mean(scores_np, axis=0) 
print(students[3], "average score:", round(average_scores_per_student[3], 2))


In [21]:
# Demonstrating the use of np.argmax() to identify the highest value scored in Math. ---

# Get index of highest math score
max_index = np.argmax(math_np)

# Use the index to fetch the student's name
max_student = students_np[max_index]

# Print
print("Highest scoring student in Math:", max_student, "with score", math_np[max_index])


Highest scoring student in Math: Safiyyah with score 90


In [20]:
# Demonstrating the use of np.argmin() to identify the lowest value scored in Math. ---

# Get index of lowest math score
min_index = np.argmin(math_np)

# Use the index to fetch the student's name
min_student = students_np[min_index]

# Print
print("Lowest scoring student in Math:", min_student, "with score", math_np[min_index])

Lowest scoring student in Math: Tara with score 56


## Conclusion

This notebook demonstrates how NumPy can be used alongside Python to analyse
student exam scores. NumPy provides powerful tools for numerical calculations
and is widely used in data analysis and scientific computing.
